sudo: required
dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  global:
    - PIPENV_VERBOSITY=-1
    - PYTHON_PIP_VERSION=18.1
    - PYTHON_PIPENV_VERSION=2018.11.26
  matrix:
    - TASKWARRIOR_VERSION=v2.5.0
    - TASKWARRIOR_VERSION=v2.5.1
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-dev cmake build-essential libgnutls28-dev uuid-dev gnutls-bin chrpath libssl-dev libfontconfig1-dev
  - pip install pip==$PYTHON_PIP_VERSION
  - pip install pipenv==$PYTHON_PIPENV_VERSION
  - git clone https://github.com/GothenburgBitFactory/taskwarrior.git
  - cd taskwarrior
  - git checkout $TASKWARRIOR_VERSION
  - cmake .
  - make
  - sudo make install
  - task --version
  - cd ../
install:
  - pipenv install --deploy --dev
script: python setup.py test
notifications:
  email: true
  on_success: change
  on_failure: always
